Refactor: 채팅방,미니투표 오류 수정 & 토큰 환불
baseball-project/backend pull request #156
Opened 2024-03-13 10:24 UTC by asapawinter

- MiniGame : start_at set추가
- MiniGameRepository : jpa 메소드 수정
- MiniGameService : 게임마다 별도로 대기, 진행, 종료 처리 추가 & 토큰 환불 구현
- GameRepository : 토큰 환불 jpa메소드 추가
- schema.sql : mini_game 테이블에 memberId, gameId, status, start_at 컬럼 추가

Ref:#153

2024-03-13 13:42 UTC, seonghye0n requested changes
고생 많으셨습니다~
리뷰 한번 확인해주세요!

2024-03-13 13:42 UTC, seonghye0n commented on src/main/java/com/example/baseballprediction/domain/chat/minigame/service/MiniGameService.java
> +    //게임이 종료된 뒤 미니투표가 해당 gameId에 남아 있을경우 토큰 환불처리
휘영님 질문이 있습니다~
야구 경기가 진짜 박빙이여서 연장하고 그러면 22시 넘어서까지 할 수도 있는데 그건 어떻게 하실 생각이신가요??

2024-03-13 13:42 UTC, seonghye0n commented on src/main/resources/h2/schema.sql
> +  start_at datetime DEFAULT NULL,
start_at이 아니고 started_at 아닐까요..?? ㅠㅠ

2024-03-14 06:10 UTC, asapawinter commented on src/main/java/com/example/baseballprediction/domain/chat/minigame/service/MiniGameService.java
> +    //게임이 종료된 뒤 미니투표가 해당 gameId에 남아 있을경우 토큰 환불처리
그럼 그럴 경우를 대비해서 유저들이 아무도 사용하지 않는 시간대인 2시에 돌도록 하겠습니다.

2024-03-14 06:10 UTC, asapawinter commented on src/main/resources/h2/schema.sql
> +  start_at datetime DEFAULT NULL,
넵 확인 했습니다 ~

2024-03-14 11:05 UTC, merged